use_frameworks!

target 'CellRegistration_Example' do
  pod 'CellRegistration', :path => '../'

  target 'CellRegistration_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
